-- ==============================================================================
-- SETUP COMPLETO DO BANCO DE DADOS - W.ASSIS CRM
-- Cole este script no SQL Editor do Supabase e clique em "Run"
-- ==============================================================================

-- 1. Tabela de Corretores/Usuários (Conectada ao Auth do Supabase)
CREATE TABLE IF NOT EXISTS corretores (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nome_completo TEXT,
    email TEXT UNIQUE,
    avatar_url TEXT,
    perfil TEXT DEFAULT 'Vendedor', -- Pode ser 'Vendedor' ou 'Gerente'
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabelas de Configurações Gerais
CREATE TABLE IF NOT EXISTS ramos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS seguradoras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS origens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS motivos_perda (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Chave→valor: webhooks n8n, token Chatwoot, etc. (RLS abaixo)
CREATE TABLE IF NOT EXISTS app_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    descricao TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Tabela de Funis e Etapas
CREATE TABLE IF NOT EXISTS funis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    tipo_funil TEXT DEFAULT 'novos',
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS etapas_funil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funil_id BIGINT REFERENCES funis(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    cor TEXT DEFAULT 'bg-blue-500',
    ordem INTEGER NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Tabela de Contatos (Clientes)
CREATE TABLE IF NOT EXISTS contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corretor_id UUID REFERENCES corretores(id),
    gerente_id UUID REFERENCES corretores(id),
    nome TEXT NOT NULL,
    documento TEXT,
    telefone TEXT,
    email TEXT,
    chatwoot_id TEXT,
    is_segurado BOOLEAN DEFAULT FALSE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Tabela de Oportunidades (Negócios/Cards)
CREATE TABLE IF NOT EXISTS oportunidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funil_id BIGINT REFERENCES funis(id),
    contato_id BIGINT REFERENCES contatos(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES contatos(id),
    corretor_id UUID REFERENCES corretores(id),
    nome_oportunidade TEXT,
    vigencia DATE,
    retorno DATE NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    origem TEXT,
    seguradora TEXT,
    -- Modelo 1:1 (um seguro por oportunidade)
    ramo_seguro TEXT,
    tipo_seguro TEXT,
    premio_liquido NUMERIC DEFAULT 0,
    comissao_percentual NUMERIC DEFAULT 0,
    agenciamento_percentual NUMERIC DEFAULT 0,
    valor_receita NUMERIC DEFAULT 0,
    indicador TEXT,
    etapa_nome TEXT NOT NULL,
    status TEXT DEFAULT 'aberto', -- 'aberto', 'ganho', 'perdido'
    motivo_perda_id UUID REFERENCES motivos_perda(id),
    motivo_perda TEXT,
    data_fechamento TIMESTAMP WITH TIME ZONE,
    excluido BOOLEAN DEFAULT FALSE,
    is_checked BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    CONSTRAINT oportunidades_identificacao_minima_chk CHECK (
        contato_id IS NOT NULL
        OR char_length(trim(COALESCE(nome_oportunidade, ''))) > 0
    ),
    CONSTRAINT oportunidades_ganho_exige_contato_chk CHECK (
        status IS DISTINCT FROM 'ganho'
        OR contato_id IS NOT NULL
    )
);

-- ==============================================================================
-- MIGRACAO: nome_oportunidade, retorno NOT NULL, CHECKs (bases criadas antes deste script)
-- ALTER TABLE public.oportunidades ADD COLUMN IF NOT EXISTS nome_oportunidade TEXT;
-- UPDATE public.oportunidades SET retorno = COALESCE(retorno, vigencia, (CURRENT_DATE AT TIME ZONE 'utc')::date) WHERE retorno IS NULL;
-- ALTER TABLE public.oportunidades ALTER COLUMN retorno SET NOT NULL;
-- (adicionar CONSTRAINTs conforme apply_migration oportunidades_nome_oportunidade_retorno_obrigatorio)
-- ==============================================================================

-- ==============================================================================
-- MIGRACAO: valor_receita e remocao de nome_segurado (nome do titular vem de contatos.nome; sem contato, usar nome_oportunidade)
-- ALTER TABLE public.oportunidades ADD COLUMN IF NOT EXISTS valor_receita NUMERIC DEFAULT 0;
-- UPDATE public.oportunidades SET valor_receita = COALESCE(premio_liquido,0) * ((COALESCE(comissao_percentual,0) + COALESCE(agenciamento_percentual,0)) / 100);
-- ALTER TABLE public.oportunidades DROP COLUMN IF EXISTS nome_segurado;
-- ==============================================================================

-- ==============================================================================
-- MIGRACAO: responsavel_id (quem negocia, opcional — titular continua em contato_id)
-- Execute no SQL Editor do Supabase se a tabela já existir sem esta coluna:
-- ALTER TABLE oportunidades ADD COLUMN IF NOT EXISTS responsavel_id BIGINT REFERENCES contatos(id);
-- ==============================================================================

-- ==============================================================================
-- MIGRACAO: gerente_id do contato (remove da oportunidade)
-- Execute no SQL Editor se a base já existir:
-- ALTER TABLE public.contatos ADD COLUMN IF NOT EXISTS gerente_id UUID REFERENCES public.corretores(id);
-- ALTER TABLE public.oportunidades DROP COLUMN IF EXISTS gerente_id;
-- ==============================================================================

-- ==============================================================================
-- MIGRACAO (opcional) PARA BASES EXISTENTES
-- Use apenas se sua tabela 'oportunidades' ainda possuir a coluna JSONB 'produtos'
-- ==============================================================================
-- 1) Copia dados do primeiro item do array JSONB para as colunas 1:1
-- UPDATE oportunidades
-- SET
--     ramo_seguro = COALESCE(ramo_seguro, produtos->0->>'ramo'),
--     tipo_seguro = COALESCE(tipo_seguro, produtos->0->>'tipo'),
--     premio_liquido = COALESCE(premio_liquido, NULLIF(produtos->0->>'premio', '')::NUMERIC, 0),
--     comissao_percentual = COALESCE(comissao_percentual, NULLIF(produtos->0->>'comissao', '')::NUMERIC, 0),
--     agenciamento_percentual = COALESCE(agenciamento_percentual, NULLIF(produtos->0->>'agenciamento', '')::NUMERIC, 0)
-- WHERE produtos IS NOT NULL
--   AND jsonb_typeof(produtos) = 'array'
--   AND jsonb_array_length(produtos) > 0;
--
-- 2) Remove a coluna antiga após validar a migração
-- ALTER TABLE oportunidades DROP COLUMN IF EXISTS produtos;

-- 6. Tabela de Histórico (Timeline)
CREATE TABLE IF NOT EXISTS historico_oportunidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oportunidade_id BIGINT REFERENCES oportunidades(id) ON DELETE CASCADE,
    criado_por UUID REFERENCES corretores(id),
    tipo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    is_log BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE historico_oportunidades
ADD COLUMN IF NOT EXISTS is_log BOOLEAN NOT NULL DEFAULT FALSE;

-- 7. Tabela de Anexos (Arquivos)
CREATE TABLE IF NOT EXISTS anexos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oportunidade_id BIGINT REFERENCES oportunidades(id) ON DELETE CASCADE,
    criado_por UUID REFERENCES corretores(id),
    nome_arquivo TEXT NOT NULL,
    url_arquivo TEXT NOT NULL,
    tamanho_bytes BIGINT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- DADOS INICIAIS PADRÃO (Opcional, mas recomendado para iniciar o sistema)
-- ==============================================================================
INSERT INTO funis (nome) VALUES ('Funil Padrão (Vendas)') ON CONFLICT DO NOTHING;
INSERT INTO etapas_funil (funil_id, nome, cor, ordem) VALUES 
(1, 'Contato Inicial', 'bg-blue-500', 1),
(1, 'Cotação Solicitada', 'bg-yellow-500', 2),
(1, 'Proposta Enviada', 'bg-orange-500', 3),
(1, 'Em Negociação', 'bg-purple-500', 4);

-- Insere alguns Ramos Padrão
INSERT INTO ramos (nome) VALUES ('Automóvel'), ('Vida'), ('Residencial'), ('Empresarial'), ('Saúde') ON CONFLICT DO NOTHING;

-- Insere motivos de perda padrão
INSERT INTO motivos_perda (nome) VALUES
('Preço fora do orçamento'),
('Cobertura não atende necessidade'),
('Perdeu o timing da decisão'),
('Escolheu concorrente'),
('Desistiu da contratação'),
('Sem retorno do cliente')
ON CONFLICT (nome) DO NOTHING;

-- ==============================================================================
-- MIGRACAO: is_checked (conferência pelo gerente). Execute se a tabela já existir:
-- ALTER TABLE oportunidades ADD COLUMN IF NOT EXISTS is_checked BOOLEAN NOT NULL DEFAULT FALSE;
-- ==============================================================================

-- ==============================================================================
-- MIGRACAO: tipo_funil em funis (novos | renovacao | pos_venda). Execute se a tabela já existir:
-- ALTER TABLE funis ADD COLUMN IF NOT EXISTS tipo_funil TEXT DEFAULT 'novos';
-- ==============================================================================

-- ==============================================================================
-- RLS — Gerente vs Vendedor (corretores.perfil = 'Gerente' vê todas as oportunidades)
-- Cadastros auxiliares (ramos, seguradoras, origens, motivos_perda, funis, etapas_funil):
-- leitura para autenticado e escrita apenas para gerente.
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.is_gerente()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT c.perfil = 'Gerente' FROM public.corretores c WHERE c.id = auth.uid()),
    false
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_gerente() TO authenticated;

-- Vendedor não altera is_checked (apenas gerente); reforço no UPDATE.
CREATE OR REPLACE FUNCTION public.oportunidades_trg_preservar_is_checked()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NOT public.is_gerente() THEN
    IF NEW.is_checked IS DISTINCT FROM OLD.is_checked THEN
      NEW.is_checked := OLD.is_checked;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_oportunidades_preservar_is_checked ON public.oportunidades;
CREATE TRIGGER tr_oportunidades_preservar_is_checked
  BEFORE UPDATE ON public.oportunidades
  FOR EACH ROW
  EXECUTE PROCEDURE public.oportunidades_trg_preservar_is_checked();

ALTER TABLE public.corretores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contatos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oportunidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historico_oportunidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anexos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ramos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seguradoras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.origens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motivos_perda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.funis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.etapas_funil ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

-- migracoes auxiliares para bases existentes
ALTER TABLE public.oportunidades ADD COLUMN IF NOT EXISTS motivo_perda_id UUID REFERENCES public.motivos_perda(id);

-- config tables (read authenticated, write manager only)
DROP POLICY IF EXISTS "ramos_select_authenticated" ON public.ramos;
CREATE POLICY "ramos_select_authenticated" ON public.ramos
  FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "ramos_insert_gerente" ON public.ramos;
CREATE POLICY "ramos_insert_gerente" ON public.ramos
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "ramos_update_gerente" ON public.ramos;
CREATE POLICY "ramos_update_gerente" ON public.ramos
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "ramos_delete_gerente" ON public.ramos;
CREATE POLICY "ramos_delete_gerente" ON public.ramos
  FOR DELETE TO authenticated
  USING (public.is_gerente());

DROP POLICY IF EXISTS "seguradoras_select_authenticated" ON public.seguradoras;
CREATE POLICY "seguradoras_select_authenticated" ON public.seguradoras
  FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "seguradoras_insert_gerente" ON public.seguradoras;
CREATE POLICY "seguradoras_insert_gerente" ON public.seguradoras
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "seguradoras_update_gerente" ON public.seguradoras;
CREATE POLICY "seguradoras_update_gerente" ON public.seguradoras
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "seguradoras_delete_gerente" ON public.seguradoras;
CREATE POLICY "seguradoras_delete_gerente" ON public.seguradoras
  FOR DELETE TO authenticated
  USING (public.is_gerente());

DROP POLICY IF EXISTS "origens_select_authenticated" ON public.origens;
CREATE POLICY "origens_select_authenticated" ON public.origens
  FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "origens_insert_gerente" ON public.origens;
CREATE POLICY "origens_insert_gerente" ON public.origens
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "origens_update_gerente" ON public.origens;
CREATE POLICY "origens_update_gerente" ON public.origens
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "origens_delete_gerente" ON public.origens;
CREATE POLICY "origens_delete_gerente" ON public.origens
  FOR DELETE TO authenticated
  USING (public.is_gerente());

DROP POLICY IF EXISTS "motivos_perda_select_authenticated" ON public.motivos_perda;
CREATE POLICY "motivos_perda_select_authenticated" ON public.motivos_perda
  FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "motivos_perda_insert_gerente" ON public.motivos_perda;
CREATE POLICY "motivos_perda_insert_gerente" ON public.motivos_perda
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "motivos_perda_update_gerente" ON public.motivos_perda;
CREATE POLICY "motivos_perda_update_gerente" ON public.motivos_perda
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "motivos_perda_delete_gerente" ON public.motivos_perda;
CREATE POLICY "motivos_perda_delete_gerente" ON public.motivos_perda
  FOR DELETE TO authenticated
  USING (public.is_gerente());

DROP POLICY IF EXISTS "app_config_select_authenticated" ON public.app_config;
CREATE POLICY "app_config_select_authenticated" ON public.app_config
  FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "app_config_insert_gerente" ON public.app_config;
CREATE POLICY "app_config_insert_gerente" ON public.app_config
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "app_config_update_gerente" ON public.app_config;
CREATE POLICY "app_config_update_gerente" ON public.app_config
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "app_config_delete_gerente" ON public.app_config;
CREATE POLICY "app_config_delete_gerente" ON public.app_config
  FOR DELETE TO authenticated
  USING (public.is_gerente());

DROP POLICY IF EXISTS "funis_select_authenticated" ON public.funis;
CREATE POLICY "funis_select_authenticated" ON public.funis
  FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "funis_insert_gerente" ON public.funis;
CREATE POLICY "funis_insert_gerente" ON public.funis
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "funis_update_gerente" ON public.funis;
CREATE POLICY "funis_update_gerente" ON public.funis
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "funis_delete_gerente" ON public.funis;
CREATE POLICY "funis_delete_gerente" ON public.funis
  FOR DELETE TO authenticated
  USING (public.is_gerente());

DROP POLICY IF EXISTS "etapas_funil_select_authenticated" ON public.etapas_funil;
CREATE POLICY "etapas_funil_select_authenticated" ON public.etapas_funil
  FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "etapas_funil_insert_gerente" ON public.etapas_funil;
CREATE POLICY "etapas_funil_insert_gerente" ON public.etapas_funil
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "etapas_funil_update_gerente" ON public.etapas_funil;
CREATE POLICY "etapas_funil_update_gerente" ON public.etapas_funil
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());
DROP POLICY IF EXISTS "etapas_funil_delete_gerente" ON public.etapas_funil;
CREATE POLICY "etapas_funil_delete_gerente" ON public.etapas_funil
  FOR DELETE TO authenticated
  USING (public.is_gerente());

-- corretores
DROP POLICY IF EXISTS "corretores_select_authenticated" ON public.corretores;
CREATE POLICY "corretores_select_authenticated" ON public.corretores
  FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_gerente());

DROP POLICY IF EXISTS "corretores_update_authenticated" ON public.corretores;
CREATE POLICY "corretores_update_authenticated" ON public.corretores
  FOR UPDATE TO authenticated
  USING (id = auth.uid() OR public.is_gerente())
  WITH CHECK (id = auth.uid() OR public.is_gerente());

-- contatos
DROP POLICY IF EXISTS "contatos_select_authenticated" ON public.contatos;
CREATE POLICY "contatos_select_authenticated" ON public.contatos
  FOR SELECT TO authenticated
  USING (public.is_gerente() OR corretor_id = auth.uid());

DROP POLICY IF EXISTS "contatos_insert_authenticated" ON public.contatos;
CREATE POLICY "contatos_insert_authenticated" ON public.contatos
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente() OR corretor_id = auth.uid());

DROP POLICY IF EXISTS "contatos_update_authenticated" ON public.contatos;
CREATE POLICY "contatos_update_authenticated" ON public.contatos
  FOR UPDATE TO authenticated
  USING (public.is_gerente() OR corretor_id = auth.uid())
  WITH CHECK (public.is_gerente() OR corretor_id = auth.uid());

DROP POLICY IF EXISTS "contatos_delete_authenticated" ON public.contatos;
CREATE POLICY "contatos_delete_authenticated" ON public.contatos
  FOR DELETE TO authenticated
  USING (public.is_gerente());

-- oportunidades
DROP POLICY IF EXISTS "oportunidades_select_authenticated" ON public.oportunidades;
CREATE POLICY "oportunidades_select_authenticated" ON public.oportunidades
  FOR SELECT TO authenticated
  USING (public.is_gerente() OR corretor_id = auth.uid());

DROP POLICY IF EXISTS "oportunidades_insert_authenticated" ON public.oportunidades;
CREATE POLICY "oportunidades_insert_authenticated" ON public.oportunidades
  FOR INSERT TO authenticated
  WITH CHECK (public.is_gerente() OR corretor_id = auth.uid());

DROP POLICY IF EXISTS "oportunidades_update_gerente" ON public.oportunidades;
CREATE POLICY "oportunidades_update_gerente" ON public.oportunidades
  FOR UPDATE TO authenticated
  USING (public.is_gerente())
  WITH CHECK (public.is_gerente());

DROP POLICY IF EXISTS "oportunidades_update_vendedor" ON public.oportunidades;
CREATE POLICY "oportunidades_update_vendedor" ON public.oportunidades
  FOR UPDATE TO authenticated
  USING (
    auth.uid() = corretor_id
    AND (COALESCE(status, 'aberto') NOT IN ('ganho', 'perdido'))
  )
  WITH CHECK (auth.uid() = corretor_id);

-- historico (acesso quando a oportunidade é visível)
DROP POLICY IF EXISTS "historico_select_authenticated" ON public.historico_oportunidades;
CREATE POLICY "historico_select_authenticated" ON public.historico_oportunidades
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.oportunidades o
      WHERE o.id = historico_oportunidades.oportunidade_id
        AND (public.is_gerente() OR o.corretor_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "historico_insert_authenticated" ON public.historico_oportunidades;
CREATE POLICY "historico_insert_authenticated" ON public.historico_oportunidades
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.oportunidades o
      WHERE o.id = historico_oportunidades.oportunidade_id
        AND (public.is_gerente() OR o.corretor_id = auth.uid())
    )
    AND criado_por = auth.uid()
  );

-- anexos
DROP POLICY IF EXISTS "anexos_select_authenticated" ON public.anexos;
CREATE POLICY "anexos_select_authenticated" ON public.anexos
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.oportunidades o
      WHERE o.id = anexos.oportunidade_id
        AND (public.is_gerente() OR o.corretor_id = auth.uid())
    )
  );

DROP POLICY IF EXISTS "anexos_insert_authenticated" ON public.anexos;
CREATE POLICY "anexos_insert_authenticated" ON public.anexos
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.oportunidades o
      WHERE o.id = anexos.oportunidade_id
        AND (public.is_gerente() OR o.corretor_id = auth.uid())
    )
    AND criado_por = auth.uid()
  );

DROP POLICY IF EXISTS "anexos_delete_authenticated" ON public.anexos;
CREATE POLICY "anexos_delete_authenticated" ON public.anexos
  FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.oportunidades o
      WHERE o.id = anexos.oportunidade_id
        AND (public.is_gerente() OR o.corretor_id = auth.uid())
    )
  );

-- ==============================================================================
-- STORAGE CONFIGURATION (LGPD Compliance)
-- ==============================================================================
-- Configure the arquivos_crm bucket manually here if you haven't via Dashboard.
-- Requires `storage` schema access.
INSERT INTO storage.buckets (id, name, public) 
VALUES ('arquivos_crm', 'arquivos_crm', false)
ON CONFLICT (id) DO UPDATE SET public = false;

DROP POLICY IF EXISTS "Acesso Livre 14atd39_0" ON storage.objects;
DROP POLICY IF EXISTS "Acesso Livre 14atd39_1" ON storage.objects;
DROP POLICY IF EXISTS "Acesso Livre 14atd39_2" ON storage.objects;
DROP POLICY IF EXISTS "Acesso Livre 14atd39_3" ON storage.objects;

DROP POLICY IF EXISTS "arquivos_crm_select_authenticated" ON storage.objects;
CREATE POLICY "arquivos_crm_select_authenticated" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'arquivos_crm');

DROP POLICY IF EXISTS "arquivos_crm_insert_authenticated" ON storage.objects;
CREATE POLICY "arquivos_crm_insert_authenticated" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'arquivos_crm');

DROP POLICY IF EXISTS "arquivos_crm_update_authenticated" ON storage.objects;
CREATE POLICY "arquivos_crm_update_authenticated" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'arquivos_crm')
  WITH CHECK (bucket_id = 'arquivos_crm');

DROP POLICY IF EXISTS "arquivos_crm_delete_authenticated" ON storage.objects;
CREATE POLICY "arquivos_crm_delete_authenticated" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'arquivos_crm');

-- Configure the avatares bucket (public for UI display)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatares', 'avatares', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "avatares_public_read" ON storage.objects;
CREATE POLICY "avatares_public_read" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'avatares');

DROP POLICY IF EXISTS "avatares_insert_auth" ON storage.objects;
CREATE POLICY "avatares_insert_auth" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'avatares');

DROP POLICY IF EXISTS "avatares_update_auth" ON storage.objects;
CREATE POLICY "avatares_update_auth" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'avatares');
