-- ==============================================================================
-- SETUP COMPLETO DO BANCO DE DADOS - W.ASSIS CRM
-- Cole este script no SQL Editor do Supabase e clique em "Run"
-- ==============================================================================

-- 1. Tabela de Corretores/Usuários (Conectada ao Auth do Supabase)
CREATE TABLE IF NOT EXISTS corretores (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nome_completo TEXT,
    email TEXT UNIQUE,
    avatar_url TEXT,
    perfil TEXT DEFAULT 'Vendedor', -- Pode ser 'Vendedor' ou 'Gerente'
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabelas de Configurações Gerais
CREATE TABLE IF NOT EXISTS ramos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS seguradoras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS origens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE
);

-- 3. Tabela de Funis e Etapas
CREATE TABLE IF NOT EXISTS funis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS etapas_funil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funil_id BIGINT REFERENCES funis(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    cor TEXT DEFAULT 'bg-blue-500',
    ordem INTEGER NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Tabela de Contatos (Clientes)
CREATE TABLE IF NOT EXISTS contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corretor_id UUID REFERENCES corretores(id),
    nome TEXT NOT NULL,
    documento TEXT,
    telefone TEXT,
    email TEXT,
    chatwoot_id TEXT,
    is_segurado BOOLEAN DEFAULT FALSE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Tabela de Oportunidades (Negócios/Cards)
CREATE TABLE IF NOT EXISTS oportunidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funil_id BIGINT REFERENCES funis(id),
    contato_id BIGINT REFERENCES contatos(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES contatos(id),
    corretor_id UUID REFERENCES corretores(id),
    gerente_id UUID REFERENCES corretores(id),
    nome_segurado TEXT NOT NULL,
    vigencia DATE,
    retorno DATE,
    ativo BOOLEAN DEFAULT TRUE,
    origem TEXT,
    seguradora TEXT,
    -- Modelo 1:1 (um seguro por oportunidade)
    ramo_seguro TEXT,
    tipo_seguro TEXT,
    premio_liquido NUMERIC DEFAULT 0,
    comissao_percentual NUMERIC DEFAULT 0,
    agenciamento_percentual NUMERIC DEFAULT 0,
    indicador TEXT,
    etapa_nome TEXT NOT NULL,
    status TEXT DEFAULT 'aberto', -- 'aberto', 'ganho', 'perdido'
    motivo_perda TEXT,
    data_fechamento TIMESTAMP WITH TIME ZONE,
    excluido BOOLEAN DEFAULT FALSE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- MIGRACAO: responsavel_id (quem negocia, opcional — titular continua em contato_id)
-- Execute no SQL Editor do Supabase se a tabela já existir sem esta coluna:
-- ALTER TABLE oportunidades ADD COLUMN IF NOT EXISTS responsavel_id BIGINT REFERENCES contatos(id);
-- ==============================================================================

-- ==============================================================================
-- MIGRACAO (opcional) PARA BASES EXISTENTES
-- Use apenas se sua tabela 'oportunidades' ainda possuir a coluna JSONB 'produtos'
-- ==============================================================================
-- 1) Copia dados do primeiro item do array JSONB para as colunas 1:1
-- UPDATE oportunidades
-- SET
--     ramo_seguro = COALESCE(ramo_seguro, produtos->0->>'ramo'),
--     tipo_seguro = COALESCE(tipo_seguro, produtos->0->>'tipo'),
--     premio_liquido = COALESCE(premio_liquido, NULLIF(produtos->0->>'premio', '')::NUMERIC, 0),
--     comissao_percentual = COALESCE(comissao_percentual, NULLIF(produtos->0->>'comissao', '')::NUMERIC, 0),
--     agenciamento_percentual = COALESCE(agenciamento_percentual, NULLIF(produtos->0->>'agenciamento', '')::NUMERIC, 0)
-- WHERE produtos IS NOT NULL
--   AND jsonb_typeof(produtos) = 'array'
--   AND jsonb_array_length(produtos) > 0;
--
-- 2) Remove a coluna antiga após validar a migração
-- ALTER TABLE oportunidades DROP COLUMN IF EXISTS produtos;

-- 6. Tabela de Histórico (Timeline)
CREATE TABLE IF NOT EXISTS historico_oportunidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oportunidade_id BIGINT REFERENCES oportunidades(id) ON DELETE CASCADE,
    criado_por UUID REFERENCES corretores(id),
    tipo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. Tabela de Anexos (Arquivos)
CREATE TABLE IF NOT EXISTS anexos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oportunidade_id BIGINT REFERENCES oportunidades(id) ON DELETE CASCADE,
    criado_por UUID REFERENCES corretores(id),
    nome_arquivo TEXT NOT NULL,
    url_arquivo TEXT NOT NULL,
    tamanho_bytes BIGINT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- DADOS INICIAIS PADRÃO (Opcional, mas recomendado para iniciar o sistema)
-- ==============================================================================
INSERT INTO funis (nome) VALUES ('Funil Padrão (Vendas)') ON CONFLICT DO NOTHING;
INSERT INTO etapas_funil (funil_id, nome, cor, ordem) VALUES 
(1, 'Contato Inicial', 'bg-blue-500', 1),
(1, 'Cotação Solicitada', 'bg-yellow-500', 2),
(1, 'Proposta Enviada', 'bg-orange-500', 3),
(1, 'Em Negociação', 'bg-purple-500', 4);

-- Insere alguns Ramos Padrão
INSERT INTO ramos (nome) VALUES ('Automóvel'), ('Vida'), ('Residencial'), ('Empresarial'), ('Saúde') ON CONFLICT DO NOTHING;
